# Using the node alpine image
image: alpine:3.7

# Name the stages involved in the pipeline
stages:
  - deploy

deploy_stg:
  stage: deploy
  variables:
    PUBLIC_URL: /
  environment:
    name: staging
  before_script:
    # Setup SSH deploy keys
    - apk update && apk add openssh bash
    - which ssh-agent || ( apk --update add openssh-client )
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$SSH_STG_PRIVATE_KEY")'
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh "$SSH_STG_USER"@"$SSH_STG_IP" -p "$SSH_PORT" "cd /home/ubuntu/app/frappe-bench/apps/indonesia_taxes_and_charges && SITE="$STG_SITE" && . update_itc.sh"
  when: on_success
  only:
    - develop # Only run on develop-bisa branch

deploy_prod:
  stage: deploy
  variables:
    PUBLIC_URL: /
  environment:
    name: production
  before_script:
    # Setup SSH deploy keys
    - apk update && apk add openssh bash
    - which ssh-agent || ( apk --update add openssh-client )
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$SSH_PROD_PRIVATE_KEY")'
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh "$SSH_PROD_USER"@"$SSH_PROD_IP" -p "$SSH_PROD_PORT" "cd /home/ubuntu/app_directory/frappe-bench/apps/indonesia_taxes_and_charges && SITE="$PROD_SITE" && . update_itc.sh"
  when: manual
  only:
    - master # Only run on master-bisa branch

deploy_erp_production_worker:
  stage: deploy
  environment:
    name: production
  before_script:
    - apk update && apk add bash
    - which ssh-agent || ( apk --update add openssh-client )
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$ERP_PROD_WORKER_PRIVKEY")'
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh "$ERP_PROD_WORKER_USER"@"$ERP_PROD_WORKER_IP" -p "$ERP_PROD_WORKER_PORT" "cd /home/ubuntu/frappe-bench/apps/indonesia_taxes_and_charges && SITE="$ERP_PROD_WORKER_SITE" && . update.sh"
  when:
    manual
  only:
    - master

deploy_udn_dev:
  stage: deploy
  variables:
    PUBLIC_URL: /
  environment:
    name: staging
  before_script:
    # Setup SSH deploy keys
    - apk update && apk add openssh bash
    - which ssh-agent || ( apk --update add openssh-client )
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$UDN_DEV_PRIVATE_KEY")'
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh "$UDN_DEV_USER"@"$UDN_DEV_IP" -p "$UDN_DEV_PORT" "cd /home/ubuntu/app_directory/frappe-bench/apps/indonesia_taxes_and_charges && SITE="$UDN_DEV_SITE" && . update_itc.sh"
  when: on_success
  only:
    - develop # Only run on develop-bisa branch
